name: Deploy to production
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install dpl
      - run: dpl --provider=heroku --app=${{ secrets.dmToken}} --api-key=${{secrets.dmToken}}
